FROM oraclelinux:8@sha256:224aa7eaa1c538916469fb856f72b398096226cfc1cd6eadb081165b55668a28

# Installing from oraclelinux:8 so that we can easily get the Oracle Instant Client
RUN dnf install -y oracle-instantclient-release-23ai-el8 && \
    dnf install -y oracle-instantclient-basic
