cluster:
  name: cert-manager-test

externalServices:
  prometheus:
    host: "{{prom_host}}"
    basicAuth:
      username: "{{prom_user}}"
      password: "{{prom_pass}}"
    {% if prom_path -%}
    writeEndpoint: "{{prom_path}}"
    {%- endif %}
  loki:
    host: "{{loki_host}}"
    basicAuth:
      username: "{{loki_user}}"
      password: "{{loki_pass}}"
    {% if loki_path -%}
    writeEndpoint: "{{loki_path}}"
    {%- endif %}

metrics:
  cost:
    enabled: false

opencost:
  enabled: false

test:
  attempts: 20
