---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-instant-client-libs
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Oracle Instant Client is ~200MB, so 1Gi gives us some room
  storageClassName: local-path
