apiVersion: v1
kind: Service
metadata:
  name: my-openldap-0
  labels:
    app: my-openldap
spec:
  ports:
  - port: 389
    targetPort: 389
  selector:
    statefulset.kubernetes.io/pod-name: my-openldap-0
