services:
  grafana:
    image: grafana/grafana:latest@sha256:e932bd6ed0e026595b08483cd0141e5103e1ab7ff8604839ff899b8dc54cabcb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
    ports:
     - '3000:3000'
    # attach to dbs network
    networks:
      - dbs

networks:
  dbs:
    name: dbs
    external: true
