services:
  grafana:
    image: grafana/grafana:latest@sha256:35c41e0fd0295f5d0ee5db7e780cf33506abfaf47686196f825364889dee878b
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
    ports:
     - '3000:3000'
    # attach to dbs network
    networks:
      - dbs

networks:
  dbs:
    name: dbs
    external: true
