services:

  mimir:
    image: grafana/mimir:latest@sha256:804c94deebdcbfdd1b01a3d79a26bcb2a54923b3c0b293031183008a257f99c5
    volumes:
      - ./configs/mimir:/etc/mimir-config
    entrypoint:
      - /bin/mimir
      - -config.file=/etc/mimir-config/mimir.yaml
    ports:
      - "9009:9009"
    networks:
      - dbs

  loki:
    image: grafana/loki:latest@sha256:191d4fdfb7264f16989f0a57f320872620a5a7c2ceeec6229212c4190ec49b86
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - dbs

networks:
  dbs:
    name: dbs
