cluster:
  name: gitlab-sample-app-cluster

externalServices:
  prometheus:
    host: "{{prom_host}}"
    basicAuth:
      username: "{{prom_user}}"
      password: "{{prom_pass}}"
    {% if prom_path -%}
    writeEndpoint: "{{prom_path}}"
    {%- endif %}
    {% if prom_query_path -%}
    queryEndpoint: "{{prom_query_path}}"
    {%- endif %}
  loki:
    host: "{{loki_host}}"
    basicAuth:
      username: "{{loki_user}}"
      password: "{{loki_pass}}"
    {% if loki_path -%}
    writeEndpoint: "{{loki_path}}"
    {%- endif %}


alloy-metrics:
  extraConfig: |-
    discovery.kubernetes "gitlab" {
        role = "pod"
        selectors {
            role = "pod"
            label = "app.kubernetes.io/name=gitlab"
        }
    }


logs:
  enabled: true
  extraConfig: |-
    discovery.relabel "gitlab_logs" {
      targets = discovery.kubernetes.pods.targets

      rule {
        action        = "keep"
        source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
        regex         = "gitlab"
      }
      
      rule {
        action        = "keep"
        source_labels = ["__meta_kubernetes_namespace"]
        regex         = "gitlab"
      }

      rule {
        target_label = "job"
        replacement = "integrations/gitlab"
      }
      
      rule {
        source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_name"]
        separator = "-"
        target_label = "instance"
      }
      
      rule {
        action = "replace"
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label  = "pod"
      }
    }

    loki.source.kubernetes "gitlab_logs" {
      targets    = discovery.relabel.gitlab_logs.output
      forward_to = [loki.process.gitlab_logs.receiver]
    }

    loki.process "gitlab_logs" {
      forward_to = [loki.process.logs_service.receiver]
      
      stage.cri {}
      
      stage.json {
        severity = "severity"
      }

      stage.labels {
        values = {
          severity = "",
          correlation_id = "",
          exception_class = "",
        }
      }

      stage.template {
        source   = "instance"
        template = "{% raw %}{{ .namespace }}-{{ .container }}{% endraw %}"
      }
    }

metrics:
  cost:
    enabled: false

opencost:
  enabled: false
