# jinja/templates/cloud-init-template.yaml
# Cloud-init configuration for setting up OpenLDAP Exporter and Grafana Agent

apt:
  sources:
    grafana:
      source: deb https://apt.grafana.com stable main
      keyid: 963FA27710458545
      keyserver: https://apt.grafana.com/gpg.key

packages:
- grafana-agent

runcmd:
- [ systemctl, enable, grafana-agent ]
- [ systemctl, start, grafana-agent ]

write_files:
- owner: root:root
  path: /etc/grafana-agent.yaml
  content: |
    server:
      http_listen_port: 12345

    prometheus:
      wal_directory: /tmp/grafana-agent-wal
      global:
        scrape_interval: 15s
      configs:
        - name: integrations
          scrape_configs:
            - job_name: 'openldap'
              static_configs:
                - targets: ['localhost:{{prom_port}}']

      remote_write:
        - url: "{{prom_url}}"
          basic_auth:
            username: "{{prom_user}}"
            password: "{{prom_pass}}"

    logs:
      configs:
        - name: default
          clients:
            - url: "{{loki_url}}"
              basic_auth:
                username: "{{loki_user}}"
                password: "{{loki_pass}}"
