apt:
  sources:
    grafana:
      source: deb https://apt.grafana.com stable main
      keyid: 963FA27710458545
      keyserver: https://apt.grafana.com/gpg.key
    envoy:
      source: deb https://deb.dl.getenvoy.io/public/deb/ubuntu jammy main
      keyid: 8115BA8E629CC074
      keyserver: https://deb.dl.getenvoy.io/public/gpg.8115BA8E629CC074.key

packages:
- grafana-agent-flow
- getenvoy-envoy

runcmd:
- [ sed, -e, s/CUSTOM_ARGS=.*/CUSTOM_ARGS="--server.http.listen-addr=0.0.0.0:8088"/g, -i, /etc/default/grafana-agent-flow ]
- [ systemctl, enable, grafana-agent-flow ]
- [ systemctl, start, --no-block, grafana-agent-flow ]
- [ sh, -xc, "echo $(ip r | grep default | cut -d' ' -f3) grafana.k3d.localhost loki.k3d.localhost mimir.k3d.localhost >> /etc/hosts" ]

write_files:
- owner: root:grafana-agent
  path: /etc/grafana-agent-flow.river
  content: |
    discovery.relabel "metrics_integrations_envoy" {
      targets = [{
        __address__ = "localhost:9901",
      }]

      rule {
        target_label = "instance"
        replacement  = constants.hostname
      }
    }

    prometheus.scrape "metrics_integrations_envoy" {
      targets      = discovery.relabel.metrics_integrations_envoy.output
      forward_to   = [prometheus.remote_write.grafana_cloud.receiver]
      job_name     = "integrations/envoy"
      metrics_path = "/stats/prometheus"
    }

    prometheus.remote_write "grafana_cloud" {
      endpoint {
        url = "{{prom_url}}"

        {% if prom_user and prom_pass -%}
        basic_auth {
          username = "{{prom_user}}"
          password = "{{prom_pass}}"
        }
        {%- endif %}

        queue_config { }

        metadata_config { }
      }
    }
