apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap-exporter
  template:
    metadata:
      labels:
        app: openldap-exporter
    spec:
      containers:
      - name: openldap-exporter
        image: jonnywamsley/openldap_exporter:latest
        args: ["/root/openldap_exporter", "--ldapAddr=my-openldap:389", "--ldapUser=cn=monitor,dc=example,dc=org", "--ldapPass=Not@SecurePassw0rd"]
