---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: cassandra
spec:
  serviceName: cassandra
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/app: cassandra
  template:
    metadata:
      labels:
        app.kubernetes.io/app: cassandra
        cassandra_cluster: operator-cassandra-cluster
    spec:
      containers:
        - name: cassandra
          image: docker.io/sample/apache-cassandra:0.0.1
          imagePullPolicy: Never
          env:
          - name: CASSANDRA_SEEDS
            value: "cassandra-0.cassandra.cassandra.svc.cluster.local,cassandra-1.cassandra.cassandra.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "operator-cassandra-cluster"
          - name: CASSANDRA_DC
            value: "datacenter1"
          - name: JVM_OPTS
            value: "-Xms1024M -Xmx1024M"
          - name: MAX_HEAP_SIZE
            value: "1024M"
          - name: HEAP_NEWSIZE
            value: "256M"
          - name: CASSANDRA_LISTEN_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
            - name: client
              containerPort: 9042
            - name: intra-node
              containerPort: 7000
            - name: tls-intra-node
              containerPort: 7001
            - name: jmx
              containerPort: 7199
            - name: jmx-exporter
              containerPort: 9145
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "nodetool status"
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 9042
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi 
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: cassandra
  labels:
    app.kubernetes.io/service: cassandra
spec:
  selector:
    app.kubernetes.io/app: cassandra
  ports:
    - name: jmx
      protocol: TCP
      port: 7199
      targetPort: 7199
    - name: cassandra
      protocol: TCP
      port: 7000
      targetPort: 7000
    - name: client
      protocol: TCP
      port: 9042
      targetPort: 9042
    - name: exporter
      protocol: TCP
      port: 9145
      targetPort: 9145